"use client";

import { useUser, CurrentUser } from '@/context/UserContext';

// Define the permission structure
interface ModulePermissions {
  read?: boolean;
  create?: boolean;
  update?: boolean;
  delete?: boolean;
  approve?: boolean;
  export?: boolean;
  special?: boolean; // For specific actions like "ack/escalate/close"
}

interface PermissionsMatrix {
  [roleName: string]: {
    [moduleName: string]: ModulePermissions;
  };
}

// PERMISSIONS_MATRIX: Frontend representation of role-based access control.
// Backend should always enforce actual RLS.
const PERMISSIONS_MATRIX: PermissionsMatrix = {
  'Platform Owner': {
    'Dashboard': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Issues': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Emergency Center': { read: true, create: true, update: true, delete: true, approve: true, special: true },
    'Maintenance': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Maintenance Agenda XLSX': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Finance': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Finance - Bills/Recurring/Deposits': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: true, export: true },
    'Finance - Late Fees/NSF/Reconciliation': { read: true, create: true, update: true, approve: true, export: true }, // Added create for rules
    'Finance - Reports': { read: true, export: true },
    'Board': { read: true, create: true, update: true, approve: true, export: true, special: true },
    'Board - Meetings/Votes': { read: true, create: true, update: true, approve: true },
    'Architectural Requests': { read: true, create: true, update: true, delete: true, approve: true },
    'Rules': { read: true, create: true, update: true, delete: true },
    'Rules - Violations': { read: true, create: true, update: true, delete: true }, // New module
    'Insurance': { read: true, create: true, update: true, delete: true },
    'Amenities': { read: true, create: true, update: true, delete: true },
    'Tenancy': { read: true, create: true, update: true, delete: true },
    'Tenancy - Leases': { read: true, create: true, update: true, delete: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: true, create: true, update: true, delete: true },
    'Visitor Logs': { read: true, create: true, update: true, delete: true },
    'Documents': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Communications': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Integrations': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Analytics': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Automations': { read: true, create: true, update: true, delete: true },
    'Settings': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Profile': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
    'Feedback': { read: true, create: true, update: true, delete: true, approve: true, export: true, special: true },
  },
  'Client Super-Administrator': {
    'Dashboard': { read: true },
    'Issues': { read: true, create: true, update: true, delete: true, approve: true },
    'Emergency Center': { read: true, approve: true, special: true },
    'Maintenance': { read: true, create: true, update: true, delete: true, approve: true },
    'Maintenance Agenda XLSX': { create: true, update: true, delete: true, approve: true },
    'Finance': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Bills/Recurring/Deposits': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: true, export: true },
    'Finance - Late Fees/NSF/Reconciliation': { read: true, create: true, update: true, approve: true, export: true },
    'Finance - Reports': { read: true, export: true },
    'Board': { read: true, create: true, update: true, approve: true },
    'Board - Meetings/Votes': { read: true, create: true, update: true, approve: true },
    'Architectural Requests': { read: true, create: true, update: true, approve: true },
    'Rules': { read: true, create: true, update: true },
    'Rules - Violations': { read: true, create: true, update: true, delete: true }, // New module
    'Insurance': { read: true, create: true, update: true },
    'Amenities': { read: true, create: true, update: true },
    'Tenancy': { read: true, create: true, update: true },
    'Tenancy - Leases': { read: true, create: true, update: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: true, create: true, update: true },
    'Visitor Logs': { read: true, create: true, update: true },
    'Documents': { read: true, create: true, update: true, delete: true, export: true },
    'Communications': { read: true, create: true, update: true, delete: true, approve: true },
    'Integrations': { read: true },
    'Analytics': { read: true },
    'Automations': { read: true, create: true, update: true, delete: true },
    'Settings': { read: true, create: true, update: true, delete: true, export: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true, update: true, delete: true },
  },
  'Condo Administrator': {
    'Dashboard': { read: true },
    'Issues': { read: true, create: true, update: true, delete: true, approve: true },
    'Emergency Center': { read: true, approve: true, special: true },
    'Maintenance': { read: true, create: true, update: true, delete: true, approve: true },
    'Maintenance Agenda XLSX': { create: true, update: true, delete: true, approve: true },
    'Finance': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Bills/Recurring/Deposits': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: true, export: true },
    'Finance - Late Fees/NSF/Reconciliation': { read: true, create: true, update: true, approve: true, export: true },
    'Finance - Reports': { read: true, export: true },
    'Board': { read: true, create: true, update: true, approve: true },
    'Board - Meetings/Votes': { read: true, create: true, update: true, approve: true },
    'Architectural Requests': { read: true, create: true, update: true, approve: true },
    'Rules': { read: true, create: true, update: true },
    'Rules - Violations': { read: true, create: true, update: true, delete: true }, // New module
    'Insurance': { read: true, create: true, update: true },
    'Amenities': { read: true, create: true, update: true },
    'Tenancy': { read: true, create: true, update: true },
    'Tenancy - Leases': { read: true, create: true, update: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: true, create: true, update: true },
    'Visitor Logs': { read: true, create: true, update: true },
    'Documents': { read: true, create: true, update: true, delete: true, export: true },
    'Communications': { read: true, create: true, update: true, delete: true, approve: true },
    'Integrations': { read: true },
    'Analytics': { read: true },
    'Automations': { read: true, create: true, update: true, delete: true },
    'Settings': { read: true, create: true, update: true, delete: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true, update: true, delete: true },
  },
  'Property Manager': {
    'Dashboard': { read: true },
    'Issues': { read: true, create: true, update: true, delete: true, approve: true },
    'Emergency Center': { read: true, approve: true, special: true },
    'Maintenance': { read: true, create: true, update: true, delete: true, approve: true },
    'Maintenance Agenda XLSX': { create: true, update: true, delete: true, approve: true },
    'Finance': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Bills/Recurring/Deposits': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: true, export: true },
    'Finance - Late Fees/NSF/Reconciliation': { read: true, create: true, update: true, approve: true, export: true },
    'Finance - Reports': { read: true, export: true },
    'Board': { read: true, create: true, update: true },
    'Board - Meetings/Votes': { read: true, create: true, update: true },
    'Architectural Requests': { read: true, create: true, update: true, approve: true },
    'Rules': { read: true, create: true, update: true },
    'Rules - Violations': { read: true, create: true, update: true, delete: true }, // New module
    'Insurance': { read: true, create: true, update: true },
    'Amenities': { read: true, create: true, update: true },
    'Tenancy': { read: true, create: true, update: true },
    'Tenancy - Leases': { read: true, create: true, update: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: true, create: true, update: true },
    'Visitor Logs': { read: true, create: true, update: true },
    'Documents': { read: true, create: true, update: true, delete: true, export: true },
    'Communications': { read: true, create: true, update: true, delete: true, approve: true },
    'Integrations': { read: true },
    'Analytics': { read: true },
    'Automations': { read: true, create: true, update: true, delete: true },
    'Settings': { read: true, create: true, update: true, delete: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true, update: true, delete: true },
  },
  'Accountant': {
    'Dashboard': { read: true },
    'Issues': { read: false },
    'Emergency Center': { read: false },
    'Maintenance': { read: false },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Bills/Recurring/Deposits': { read: true, create: true, update: true, delete: true, approve: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: true, export: true },
    'Finance - Late Fees/NSF/Reconciliation': { read: true, create: true, update: true, approve: true, export: true },
    'Finance - Reports': { read: true, export: true },
    'Board': { read: false },
    'Board - Meetings/Votes': { read: false },
    'Architectural Requests': { read: false },
    'Rules': { read: true },
    'Rules - Violations': { read: true }, // New module
    'Insurance': { read: true },
    'Amenities': { read: false },
    'Tenancy': { read: true },
    'Tenancy - Leases': { read: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: true },
    'Visitor Logs': { read: false },
    'Documents': { read: true, create: true, export: true },
    'Communications': { read: true, create: true, approve: true },
    'Integrations': { read: false },
    'Analytics': { read: true },
    'Automations': { read: false },
    'Settings': { read: true, update: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
  'Board Member': {
    'Dashboard': { read: true },
    'Issues': { read: true },
    'Emergency Center': { read: true },
    'Maintenance': { read: true },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: true, export: true },
    'Finance - Bills/Recurring/Deposits': { read: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: false },
    'Finance - Late Fees/NSF/Reconciliation': { read: false },
    'Finance - Reports': { read: true, export: true },
    'Board': { read: true, create: true, update: true, approve: true },
    'Board - Meetings/Votes': { read: true, create: true, update: true, approve: true },
    'Architectural Requests': { read: true, create: true, update: true, approve: true },
    'Rules': { read: true },
    'Rules - Violations': { read: true }, // New module
    'Insurance': { read: true },
    'Amenities': { read: true },
    'Tenancy': { read: true },
    'Tenancy - Leases': { read: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: true },
    'Visitor Logs': { read: true },
    'Documents': { read: true, export: true },
    'Communications': { read: true },
    'Integrations': { read: false },
    'Analytics': { read: true },
    'Automations': { read: false },
    'Settings': { read: true, update: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
  'Owner': {
    'Dashboard': { read: true },
    'Issues': { read: true, create: true, update: true },
    'Emergency Center': { read: true },
    'Maintenance': { read: true },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: true, export: true },
    'Finance - Bills/Recurring/Deposits': { read: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: false },
    'Finance - Late Fees/NSF/Reconciliation': { read: false },
    'Finance - Reports': { read: false },
    'Board': { read: false },
    'Board - Meetings/Votes': { read: false },
    'Architectural Requests': { read: true, create: true, update: true },
    'Rules': { read: true },
    'Rules - Violations': { read: true }, // New module
    'Insurance': { read: true },
    'Amenities': { read: true },
    'Tenancy': { read: true, create: true, update: true },
    'Tenancy - Leases': { read: true, create: true, update: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: false },
    'Visitor Logs': { read: true, create: true },
    'Documents': { read: true, export: true },
    'Communications': { read: true },
    'Integrations': { read: false },
    'Analytics': { read: false },
    'Automations': { read: false },
    'Settings': { read: true, update: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
  'Tenant': {
    'Dashboard': { read: true },
    'Issues': { read: true, create: true, update: true },
    'Emergency Center': { read: true },
    'Maintenance': { read: true },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: true, export: true },
    'Finance - Bills/Recurring/Deposits': { read: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: false },
    'Finance - Late Fees/NSF/Reconciliation': { read: false },
    'Finance - Reports': { read: false },
    'Board': { read: false },
    'Board - Meetings/Votes': { read: false },
    'Architectural Requests': { read: true, create: true, update: true },
    'Rules': { read: true },
    'Rules - Violations': { read: true }, // New module
    'Insurance': { read: true },
    'Amenities': { read: true },
    'Tenancy': { read: true, create: true, update: true },
    'Tenancy - Leases': { read: true, create: true, update: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: false },
    'Visitor Logs': { read: true, create: true },
    'Documents': { read: true, export: true },
    'Communications': { read: true },
    'Integrations': { read: false },
    'Analytics': { read: false },
    'Automations': { read: false },
    'Settings': { read: true, update: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
  'Vendor / Service Provider': {
    'Dashboard': { read: true },
    'Issues': { read: true, update: true },
    'Emergency Center': { read: false },
    'Maintenance': { read: true, update: true },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: false },
    'Finance - Bills/Recurring/Deposits': { read: false },
    'Finance - Statements': { read: false },
    'Finance - Ledger/Trial Balance': { read: false },
    'Finance - Late Fees/NSF/Reconciliation': { read: false },
    'Finance - Reports': { read: false },
    'Board': { read: false },
    'Board - Meetings/Votes': { read: false },
    'Architectural Requests': { read: false },
    'Rules': { read: true },
    'Rules - Violations': { read: false }, // New module
    'Insurance': { read: false },
    'Amenities': { read: false },
    'Tenancy': { read: false },
    'Tenancy - Leases': { read: false },
    'Tenancy - Unit Statements': { read: false },
    'Portfolio Management': { read: false },
    'Visitor Logs': { read: true, create: true, update: true },
    'Documents': { read: true },
    'Communications': { read: true },
    'Integrations': { read: false },
    'Analytics': { read: false },
    'Automations': { read: false },
    'Settings': { read: true, update: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
  'Emergency Agent': {
    'Dashboard': { read: true },
    'Issues': { read: true, approve: true, update: true },
    'Emergency Center': { read: true, approve: true, special: true, update: true },
    'Maintenance': { read: true },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: false },
    'Finance - Bills/Recurring/Deposits': { read: false },
    'Finance - Statements': { read: false },
    'Finance - Ledger/Trial Balance': { read: false },
    'Finance - Late Fees/NSF/Reconciliation': { read: false },
    'Finance - Reports': { read: false },
    'Board': { read: false },
    'Board - Meetings/Votes': { read: false },
    'Architectural Requests': { read: false },
    'Rules': { read: true },
    'Rules - Violations': { read: true, create: true, update: true }, // New module
    'Insurance': { read: true },
    'Amenities': { read: false },
    'Tenancy': { read: false },
    'Tenancy - Leases': { read: false },
    'Tenancy - Unit Statements': { read: false },
    'Portfolio Management': { read: false },
    'Visitor Logs': { read: true, create: true, update: true },
    'Documents': { read: true },
    'Communications': { read: true },
    'Integrations': { read: false },
    'Analytics': { read: false },
    'Automations': { read: false },
    'Settings': { read: true, update: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
  'Concierge / Front Desk / Security': {
    'Dashboard': { read: true },
    'Issues': { read: true, create: true, update: true },
    'Emergency Center': { read: true, approve: true, special: true },
    'Maintenance': { read: true, create: true },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: false },
    'Finance - Bills/Recurring/Deposits': { read: false },
    'Finance - Statements': { read: false },
    'Finance - Ledger/Trial Balance': { read: false },
    'Finance - Late Fees/NSF/Reconciliation': { read: false },
    'Finance - Reports': { read: false },
    'Board': { read: false },
    'Board - Meetings/Votes': { read: false },
    'Architectural Requests': { read: false },
    'Rules': { read: true },
    'Rules - Violations': { read: true, create: true, update: true }, // New module
    'Insurance': { read: false },
    'Amenities': { read: true, create: true, update: true },
    'Tenancy': { read: true, create: true, update: true },
    'Tenancy - Leases': { read: true, create: true, update: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: false },
    'Visitor Logs': { read: true, create: true, update: true },
    'Documents': { read: true },
    'Communications': { read: true, create: true },
    'Integrations': { read: false },
    'Analytics': { read: false },
    'Automations': { read: false },
    'Settings': { read: true, update: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
  'Building Maintenance Technician': {
    'Dashboard': { read: true },
    'Issues': { read: true, update: true },
    'Emergency Center': { read: true },
    'Maintenance': { read: true, create: true, update: true },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: false },
    'Finance - Bills/Recurring/Deposits': { read: false },
    'Finance - Statements': { read: false },
    'Finance - Ledger/Trial Balance': { read: false },
    'Finance - Late Fees/NSF/Reconciliation': { read: false },
    'Finance - Reports': { read: false },
    'Board': { read: false },
    'Board - Meetings/Votes': { read: false },
    'Architectural Requests': { read: false },
    'Rules': { read: true },
    'Rules - Violations': { read: false }, // New module
    'Insurance': { read: false },
    'Amenities': { read: false },
    'Tenancy': { read: false },
    'Tenancy - Leases': { read: false },
    'Tenancy - Unit Statements': { read: false },
    'Portfolio Management': { read: false },
    'Visitor Logs': { read: false },
    'Documents': { read: true },
    'Communications': { read: true },
    'Integrations': { read: false },
    'Analytics': { read: false },
    'Automations': { read: false },
    'Settings': { read: true, update: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
  'Read-Only Auditor': {
    'Dashboard': { read: true },
    'Issues': { read: true },
    'Emergency Center': { read: true },
    'Maintenance': { read: true },
    'Maintenance Agenda XLSX': { read: false },
    'Finance': { read: true, export: true },
    'Finance - Bills/Recurring/Deposits': { read: true, export: true },
    'Finance - Statements': { read: true, export: true },
    'Finance - Ledger/Trial Balance': { read: true, export: true },
    'Finance - Late Fees/NSF/Reconciliation': { read: false },
    'Finance - Reports': { read: true, export: true },
    'Board': { read: true },
    'Board - Meetings/Votes': { read: true },
    'Architectural Requests': { read: true },
    'Rules': { read: true },
    'Rules - Violations': { read: true }, // New module
    'Insurance': { read: true },
    'Amenities': { read: true },
    'Tenancy': { read: true },
    'Tenancy - Leases': { read: true },
    'Tenancy - Unit Statements': { read: true, export: true },
    'Portfolio Management': { read: true },
    'Visitor Logs': { read: true },
    'Documents': { read: true, export: true },
    'Communications': { read: true },
    'Integrations': { read: false },
    'Analytics': { read: true },
    'Automations': { read: false },
    'Settings': { read: true },
    'Profile': { read: true, update: true },
    'Feedback': { read: true, create: true },
  },
};

export const useAuth = () => {
  const { currentUser } = useUser();

  const checkPermission = (moduleName: string, action: keyof ModulePermissions): boolean => {
    if (!currentUser || !currentUser.roles || currentUser.roles.length === 0) {
      return false;
    }

    // If any of the user's roles grant the permission, then they have it
    for (const userRole of currentUser.roles) {
      const rolePermissions = PERMISSIONS_MATRIX[userRole.name];
      if (rolePermissions) {
        const modulePermissions = rolePermissions[moduleName];
        if (modulePermissions && modulePermissions[action]) {
          return true;
        }
      }
    }
    return false;
  };

  // Helper functions for common actions
  const canRead = (moduleName: string) => checkPermission(moduleName, 'read');
  const canCreate = (moduleName: string) => checkPermission(moduleName, 'create');
  const canUpdate = (moduleName: string) => checkPermission(moduleName, 'update');
  const canDelete = (moduleName: string) => checkPermission(moduleName, 'delete');
  const canApprove = (moduleName: string) => checkPermission(moduleName, 'approve');
  const canExport = (moduleName: string) => checkPermission(moduleName, 'export');
  const canPerformSpecial = (moduleName: string) => checkPermission(moduleName, 'special');

  return {
    currentUser,
    canRead,
    canCreate,
    canUpdate,
    canDelete,
    canApprove,
    canExport,
    canPerformSpecial,
  };
};